apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: el-hub-api-develop-github
spec:
  serviceAccountName: pipeline
  interceptors:
    - ref:
        name: "github"
      params:
        - name: "secretRef"
          value:
            secretName: hub-api-develop-pipeline-secret
            secretKey: WebHookSecretKey
        - name: "eventTypes"
          value: ["push"]
    - ref:
        name: "cel"
      params:
        - name: "filter"
          value: "header.match('X-GitHub-Event', 'push') && body.ref.startsWith('refs/heads/develop')"   
  bindings:
    - ref: gcpe-hub-api-develop
  template:
    ref: gcpe-hub-api-develop